In [16]:
import pandas as pd
import spacy
from time import time
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import fetch_20newsgroups

In [20]:
data = pd.read_csv('data/spam.csv', encoding='ISO-8859-1')
data.head(10)

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()

In [53]:
list=[]
for doc in data['v2']:
    list.append(doc)

In [54]:
for i in list:
    doc2 = nlp(i)
    [token for token in doc2]

In [42]:
my_stopwords = nlp.Defaults.stop_words
type(my_stopwords)

set

In [55]:
for i in list:
    doc2 = nlp(i)
    [token for token in doc2 if token.lower_ not in my_stopwords]

In [56]:
import spacy
from spacy.lookups import Lookups

nlp = spacy.load("en_core_web_sm")

## lemmatization
# токенизация (получение объекта doc)
for i in list:
    doc = nlp(i)
    # лемматизация
    for word in doc:
        print(word.text, "=>", word.lemma_)
    data_lematized = [word.lemma_ for word in doc]
data_lematized

Go => go
until => until
jurong => jurong
point => point
, => ,
crazy => crazy
.. => ..
Available => available
only => only
in => in
bugis => bugis
n => n
great => great
world => world
la => la
e => e
buffet => buffet
... => ...
Cine => Cine
there => there
got => get
amore => amore
wat => wat
... => ...
Ok => ok
lar => lar
... => ...
Joking => joke
wif => wif
u => u
oni => oni
... => ...
Free => free
entry => entry
in => in
2 => 2
a => a
wkly => wkly
comp => comp
to => to
win => win
FA => FA
Cup => Cup
final => final
tkts => tkts
21st => 21st
May => May
2005 => 2005
. => .
Text => text
FA => FA
to => to
87121 => 87121
to => to
receive => receive
entry => entry
question(std => question(std
txt => txt
rate)T&C => rate)T&C
's => 's
apply => apply
08452810075over18 => 08452810075over18
's => 's
U => u
dun => dun
say => say
so => so
early => early
hor => hor
... => ...
U => u
c => c
already => already
then => then
say => say
... => ...
Nah => nah
I => I
do => do
n't => not
think => think
he 

['rofl', '.', 'its', 'true', 'to', 'its', 'name']

In [57]:
bow = count_vectorizer.fit_transform(list)
bow.shape

(5572, 25)

In [58]:
count_vectorizer.vocabulary_

{'in': 8,
 'to': 21,
 'so': 18,
 'it': 10,
 'now': 14,
 'and': 0,
 'you': 23,
 'for': 6,
 'my': 12,
 'is': 9,
 'not': 13,
 'me': 11,
 'your': 24,
 'have': 7,
 'call': 3,
 'or': 17,
 'the': 20,
 'on': 16,
 'that': 19,
 'can': 4,
 'are': 1,
 'do': 5,
 'we': 22,
 'but': 2,
 'of': 15}

In [59]:
bow.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
count_vectorizer = CountVectorizer(min_df=3)
bow = count_vectorizer.fit_transform(list)
count_vectorizer.vocabulary_

{'go': 1088,
 'until': 2574,
 'point': 1878,
 'crazy': 687,
 'available': 347,
 'only': 1759,
 'in': 1260,
 'bugis': 491,
 'great': 1111,
 'world': 2753,
 'la': 1379,
 'cine': 600,
 'there': 2437,
 'got': 1103,
 'wat': 2665,
 'ok': 1746,
 'lar': 1388,
 'joking': 1336,
 'wif': 2713,
 'oni': 1757,
 'free': 1017,
 'entry': 876,
 'wkly': 2735,
 'comp': 640,
 'to': 2482,
 'win': 2718,
 'cup': 702,
 'final': 971,
 'tkts': 2477,
 '21st': 81,
 'may': 1549,
 '2005': 78,
 'text': 2414,
 '87121': 177,
 'receive': 1988,
 'question': 1943,
 'std': 2300,
 'txt': 2543,
 'rate': 1965,
 'apply': 301,
 'dun': 833,
 'say': 2092,
 'so': 2230,
 'early': 839,
 'already': 263,
 'then': 2435,
 'nah': 1666,
 'don': 802,
 'think': 2442,
 'he': 1164,
 'goes': 1090,
 'usf': 2594,
 'lives': 1452,
 'around': 319,
 'here': 1178,
 'though': 2452,
 'freemsg': 1019,
 'hey': 1179,
 'darling': 722,
 'it': 1307,
 'been': 390,
 'week': 2682,
 'now': 1722,
 'and': 277,
 'no': 1704,
 'word': 2747,
 'back': 362,
 'like': 1437

In [61]:
count_vectorizer = CountVectorizer(ngram_range=(1,2), min_df=2)
bow = count_vectorizer.fit_transform(list)
print(count_vectorizer.vocabulary_)

{'go': 4987, 'until': 13186, 'point': 9797, 'crazy': 3245, 'available': 1709, 'only': 9202, 'in': 6095, 'bugis': 2272, 'great': 5198, 'world': 14346, 'la': 6925, 'buffet': 2271, 'cine': 2870, 'there': 12241, 'got': 5127, 'wat': 13673, 'only in': 9221, 'ok': 9033, 'lar': 6949, 'joking': 6692, 'wif': 14052, 'oni': 9198, 'ok lar': 9048, 'free': 4599, 'entry': 4069, 'wkly': 14254, 'comp': 3050, 'to': 12531, 'win': 14122, 'fa': 4230, 'cup': 3295, 'final': 4363, 'tkts': 12513, '21st': 398, 'may': 7631, '2005': 389, 'text': 11816, '87121': 751, 'receive': 10189, 'question': 10023, 'std': 11422, 'txt': 13053, 'rate': 10086, 'apply': 1435, '08452810075over18': 88, 'free entry': 4613, 'entry in': 4071, 'in wkly': 6209, 'wkly comp': 14255, 'comp to': 3053, 'to win': 12789, 'win fa': 14131, 'fa cup': 4231, 'cup final': 3296, 'final tkts': 4368, 'tkts 21st': 12514, '21st may': 399, 'may 2005': 7632, '2005 text': 390, 'text fa': 11821, 'fa to': 4232, 'to 87121': 12571, '87121 to': 753, 'to receive':

In [62]:
count_vectorizer = CountVectorizer(ngram_range=(1,2), max_features=25)
bow = count_vectorizer.fit_transform(list)
count_vectorizer.vocabulary_

{'in': 8,
 'to': 21,
 'so': 18,
 'it': 10,
 'now': 14,
 'and': 0,
 'you': 23,
 'for': 6,
 'my': 12,
 'is': 9,
 'not': 13,
 'me': 11,
 'your': 24,
 'have': 7,
 'call': 3,
 'or': 17,
 'the': 20,
 'on': 16,
 'that': 19,
 'can': 4,
 'are': 1,
 'do': 5,
 'we': 22,
 'but': 2,
 'of': 15}

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(list)
tfidf_vectorizer.vocabulary_

{'go': 3550,
 'until': 8030,
 'jurong': 4350,
 'point': 5920,
 'crazy': 2327,
 'available': 1303,
 'only': 5537,
 'in': 4087,
 'bugis': 1751,
 'great': 3634,
 'world': 8489,
 'la': 4476,
 'buffet': 1749,
 'cine': 2048,
 'there': 7645,
 'got': 3594,
 'amore': 1069,
 'wat': 8267,
 'ok': 5504,
 'lar': 4512,
 'joking': 4318,
 'wif': 8392,
 'oni': 5533,
 'free': 3358,
 'entry': 2949,
 'wkly': 8447,
 'comp': 2165,
 'to': 7756,
 'win': 8405,
 'fa': 3087,
 'cup': 2386,
 'final': 3207,
 'tkts': 7743,
 '21st': 411,
 'may': 4930,
 '2005': 402,
 'text': 7595,
 '87121': 784,
 'receive': 6297,
 'question': 6190,
 'std': 7230,
 'txt': 7933,
 'rate': 6242,
 'apply': 1156,
 '08452810075over18': 77,
 'dun': 2802,
 'say': 6633,
 'so': 7024,
 'early': 2823,
 'hor': 3927,
 'already': 1042,
 'then': 7640,
 'nah': 5238,
 'don': 2712,
 'think': 7660,
 'he': 3781,
 'goes': 3558,
 'usf': 8075,
 'lives': 4665,
 'around': 1207,
 'here': 3831,
 'though': 7680,
 'freemsg': 3365,
 'hey': 3841,
 'darling': 2443,
 'it

In [64]:
tfidf.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [65]:
TfidfVectorizer().fit_transform(list).todense()[2]

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [66]:
TfidfVectorizer(sublinear_tf=True).fit_transform(list).todense()[2]

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [67]:
doc[0].vector.shape

(96,)

In [68]:
from time import time
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import fetch_20newsgroups

In [69]:
n_samples = 2000
n_features = 1000
n_topics = 10
n_top_words = 20

In [71]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-n_top_words - 1:-1]]))

In [72]:
print("Loading dataset...")
dataset = fetch_20newsgroups(shuffle=True, random_state=1,
                             remove=('headers', 'footers', 'quotes'))
data_samples = dataset.data[:n_samples]

Loading dataset...


In [73]:
print("Extracting tf features for LDA...")
tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2,
                                max_features=n_features,
                                stop_words='english')
tf = tf_vectorizer.fit_transform(data_samples)

Extracting tf features for LDA...


In [74]:
tf.shape

(2000, 1000)

In [75]:
lda = LatentDirichletAllocation(n_components=n_topics, max_iter=20,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0).fit(tf)

In [76]:
tf_vectorizer.get_feature_names_out()

array(['00', '000', '10', '100', '11', '12', '128', '13', '130', '14',
       '15', '16', '17', '18', '19', '1992', '1993', '20', '200', '21',
       '22', '23', '24', '25', '250', '26', '27', '28', '29', '2nd', '30',
       '300', '31', '32', '33', '34', '35', '36', '37', '38', '3d', '40',
       '42', '43', '44', '45', '48', '49', '50', '500', '51', '55', '60',
       '66', '70', '72', '75', '80', '800', '86', '90', '92', '93', '__',
       'able', 'ac', 'accept', 'access', 'according', 'act', 'action',
       'actually', 'add', 'added', 'addition', 'address',
       'administration', 'advance', 'age', 'ago', 'agree', 'aids', 'air',
       'al', 'allow', 'allowed', 'alt', 'america', 'american', 'amiga',
       'analysis', 'anonymous', 'answer', 'answers', 'anti', 'anybody',
       'apartment', 'appears', 'apple', 'application', 'applications',
       'apply', 'appreciated', 'approach', 'appropriate', 'apr', 'april',
       'archive', 'area', 'areas', 'aren', 'argument', 'armenia',
  

In [77]:
lda.components_.shape

(10, 1000)

In [78]:
lda.transform(tf).shape

(2000, 10)

In [79]:
print_top_words(lda, tf_vectorizer.get_feature_names_out(), 10)

Topic #0:
edu com mail send graphics ftp pub available contact version
Topic #1:
don like just think know ve good way people right
Topic #2:
think christian book atheism new pittsburgh president like game just
Topic #3:
drive windows disk thanks use card drives hard using software
Topic #4:
hiv health aids april disease research care medical information 1993
Topic #5:
god people does jesus law say just life don israel
Topic #6:
10 55 11 15 game 12 18 team 20 19
Topic #7:
car year new bike cars good engine just price oil
Topic #8:
people said didn went did know time just like took
Topic #9:
key space government public use law encryption section keys earth
